### ISSUE TITLE
Gadget work with JIRA Cloud??

### ISSUE THREAD

**Issue by BallardGitHub** [zenoss/testrail-jira-gadgets#11]
The Testrail-jira-gadget code looks promising and will be very useful for our firm if this can work with JIRA Cloud. Please advise if the available code can be configured for JIRA cloud  and if we can set up the respective gadget for reporting from Testrail to JIRA Cloud. 

Thank you,
Ballard Team

**Comment by dyoungzenoss** [comment]
Technically it's possible, as long as the the gadget XML and .js files are on a web server that can be accessed from JIRA. However, I don't know if Atlassian allows users/admins of cloud instances to add standalone gadgets. If they do, then it should work.

**Comment by BallardGitHub** [comment]
What should we check with Atlassian? Also, can you help us set up the gadget XML and .js files on a web server?

**Comment by dyoungzenoss** [comment]
1) For Atlassian, ask if custom gadgets can be added to the gadget directory.
2) If you have testrail running locally you can use that as your web server. If you're using TestRail Cloud you can set up a local Apache web server (or IIS if you're a Windows shop). This web server needs to be accessible externally (and it works better if it supports HTTPS with a signed SSL certificate).
3) Once the web server is set up follow the [install instructions](https://github.com/zenoss/testrail-jira-gadgets/blob/master/INSTALL.md) for installing and configuring the gadget files.
