### ISSUE TITLE
project permissions

### ISSUE THREAD

**Issue by wpscollab** [zenoss/testrail-jira-gadgets#12]
On the [JIRA gadgets for TestRail forum](https://discuss.gurock.com/t/jira-gadgets-for-testrail/2918) , another user comment from March2018 states: 

> Has anyone solved the permissions and project visibility issues with the gadgets e.g. I only want a person seeing plans/projects which they have permission to see. Only the admin can see all projects, individual access is added when they are working on the project and removed asap. But the gadget gives everyone visibility of all projects

Can you please verify whether this has been fixed? Does every JIRA user see information about all TestRail projects, even TestRail projects that they do not have permissions in TestRail to see?

**Comment by dyoungzenoss** [comment]
It's not something that can be easily fixed with a standalone gadget, and there's a possibility it's not fixable at all with a standalone gadget. This issue would probably require a full plug-in that could do some sort of Oauth authentication for the user viewing the gadget data.

**Comment by wpscollab** [comment]
OK, thanks for confirming. I'll close this issue.
