### ISSUE TITLE
Can't locate Config/Properties.pm in @INC

### ISSUE THREAD

**Issue by satish20349** [zenoss/testrail-jira-gadgets#13]
i've tried to run this files in perl getting below error. 

**"Can't locate Config/Properties.pm in @INC (you may need to install the Config::Properties module) (@INC contains: C:/Perl64/site/lib C:/Perl64/lib) at generate-activity-gadget-xml.pl line 8.
BEGIN failed--compilation aborted at generate-activity-gadget-xml.pl line 8."**
![testrail perl error](https://user-images.githubusercontent.com/52167095/71592129-449cda00-2aec-11ea-856c-0c9902e6a4ba.png)

**Comment by dyoungzenoss** [comment]
In the install page (https://github.com/zenoss/testrail-jira-gadgets/blob/master/INSTALL.md) there is a list of Perl modules that must be installed for those scripts to work. They are:

- Config::Properties
- MIME::Base64
- JSON
- REST::Client
- HTML::Parser
