### ISSUE TITLE
Unable to retrieve the list of statuses on Jira server 

### ISSUE THREAD

**Issue by rmoshe** [zenoss/testrail-jira-gadgets#4]
1. Followed all the instructions on https://github.com/zenoss/testrail-jira-gadgets/blob/master/INSTALL.md

2. All .pl files are running and .xml files are created with my Testrail data
3. All XML path's are added as gadgates to Jira, and can be added.
4. Once Added, I get the following:
"Unable to retrieve the list of statuses"
See below a screenshot of the gadget inside Jira and the Gadgets directory containing the testrail gadgets:
https://cdn-business.discourse.org/uploads/gurock/original/2X/1/164ea6f71d41d5dce7b9f8dd27374ad9ffc12672.png

**My configuration is:**
1. Jira Server v6 configured as HTTP
2. local Gadget server - RedHat7 running httpd - HTTP
3. Testrail cloud - HTTPS

Jira server can access both TestRail cloud and Gadget server 
Gadget server can access both TestRail cloud and Jira server

To Don Young request, I have ran the below curl from both the gadget server and Jira server - both returned with the same result.
real user and domain name were replaced with xxxxx (no typoes there as everything was replaced from default configuration using sed):

```[root@vm-qa-nfs scripts]# curl -v -H "Content-Type: application/json" -X GET -u moshe@XXX.com:guest https://XXXX.testrail.com/index.php?/api/v2/get_statuses | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to XXXX.testrail.com port 443 (#0)
*   Trying 52.1.103.218...
* Connected to XXXX.testrail.com (52.1.103.218) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=*.testrail.com,OU=IT,O=Gurock Software GmbH,L=Berlin,C=DE
* 	start date: Aug 17 00:00:00 2014 GMT
* 	expire date: Nov 03 12:00:00 2017 GMT
* 	common name: *.testrail.com
* 	issuer: CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
* Server auth using Basic with user 'XXXXXX'
> GET /index.php?/api/v2/get_statuses HTTP/1.1
> Authorization: Basic bW9zaGVAcmVkdXhpby5jb206Z3Vlc3Q=
> User-Agent: curl/7.29.0
> Host: XXXXX.testrail.com
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Mon, 09 Jan 2017 18:47:06 GMT
< Server: Apache
< Content-Length: 830
< Connection: keep-alive
< 
{ [data not shown]
100   830  100   830    0     0    620      0  0:00:01  0:00:01 --:--:--   620
* Connection #0 to host XXXXX.testrail.com left intact
[
    {
        "color_bright": 12709313,
        "color_dark": 6667107,
        "color_medium": 9820525,
        "id": 1,
        "is_final": true,
        "is_system": true,
        "is_untested": false,
        "label": "Passed",
        "name": "passed"
    },
    {
        "color_bright": 14737632,
        "color_dark": 9474192,
        "color_medium": 13684944,
        "id": 2,
        "is_final": true,
        "is_system": true,
        "is_untested": false,
        "label": "Blocked",
        "name": "blocked"
    },
    {
        "color_bright": 15790320,
        "color_dark": 11579568,
        "color_medium": 15395562,
        "id": 3,
        "is_final": false,
        "is_system": true,
        "is_untested": true,
        "label": "Untested",
        "name": "untested"
    },
    {
        "color_bright": 16448182,
        "color_dark": 13026868,
        "color_medium": 15593088,
        "id": 4,
        "is_final": false,
        "is_system": true,
        "is_untested": false,
        "label": "Retest",
        "name": "retest"
    },
    {
        "color_bright": 16631751,
        "color_dark": 14250867,
        "color_medium": 15829135,
        "id": 5,
        "is_final": true,
        "is_system": true,
        "is_untested": false,
        "label": "Failed",
        "name": "failed"
    }
]
```

Example Gadget XML:
```<Module>
<ModulePrefs title="TestRail: Milestone Status" description="Testing status from TestRail for a specific milestone" author="Don Young" author_email="dyoung@zenoss.com" thumbnail="__UP_gadgetURL__/images/testrail-milestone-gadget-thumbnail.png" height="330">
<Require feature="dynamic-height"/>
<Require feature="settitle"/>
<Require feature="minimessage"/>
<Optional feature="gadget-directory">
<Param name="categories">Other</Param>
</Optional>
</ModulePrefs>
<UserPref name="projectMilestoneIDList" display_name="(Project) Milestone" datatype="enum" default_value="1|10">
<EnumValue value="1|10" display_value="(XXXX) V3.0 Integration"/>
<EnumValue value="1|12" display_value="(XXXX) V3.0GA"/>
<EnumValue value="1|13" display_value="(XXXX) V3.0GA\V3-Cycle1"/>
<EnumValue value="1|14" display_value="(XXXX) V3.0GA\V3-Cycle2"/>
<EnumValue value="1|15" display_value="(XXXX) V3.0GA\V3-Cycle3"/>
</UserPref>
<UserPref name="testRailURL" display_name="TestRail URL" datatype="hidden" default_value="https://XXXX.testrail.com/"/>
<UserPref name="gadgetURL" display_name="Gadget Web Server URL" datatype="hidden" default_value="http://vm-qa-nfs/"/>
<Content type="html" view="default">
<![CDATA[
<div id="milestoneChart"></div> <div id="milestoneCaption" style="text-align: center; font-weight: bold"></div> <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> <script type="text/javascript" src="__UP_gadgetURL__/gadgets/testrail-milestone-summary.js"></script> <p id="disclaimer" style='text-align: center; font-size: 11px; font-style:italic'></p>
]]>
</Content>
</Module>
```

**Comment by dyoungzenoss** [comment]
Are there any error messages in the TestRail log?  I'm not sure if it's the same in the cloud version, but in the onsite version the logs are in **Administration -> System Log**

**Comment by rmoshe** [comment]
Nothing like that... I have no idea where TestRail logs are....

**Comment by rmoshe** [comment]
Do you see anything in the xml format that is wrong ?

**Comment by dyoungzenoss** [comment]
The XML file looks fine. And since there's milestones listed then the Perl scripts are working just fine.

Also, since your instance is a cloud instance I would guess Gurock would have to check the TestRail logs.

(In my next comment I'm going to walk you through debugging this in the Chrome browser.)

**Comment by dyoungzenoss** [comment]
Debugging in the Chrome browser:

**NOTE:** The following line numbers are for the TestRail: Milestone Status gadget.

1. Browse to the JIRA dashboard with the TestRail gadget
1. Ctrl-Shift-J to open the developer console
1. Click the Sources tab
1. Ctrl-P to open a file
1. In the file box type _testrail_ which will show the TestRail gadget javascript file (testrail-milestone-summary.js) at the top of the list. Click on that file to open it.
1. Put a breakpoint on the following line by scrolling down to line 83 and clicking the 83.<br><br>_for (var i = 0; i < responseLength; i++) {_<br><br>
1. Refresh the page. The page should pause in the middle of the refresh with a small **Paused in debugger** message. Also, you should see some of the response values for the function calls highlighted in the source.  For example, line 73 should show the response object passed in. On that line ensure the _rc_ value is 200.
1. On line 79 ensure the responseLength value is > 0.

If the rc value on line 73 isn't 200 and the responseLength on line 79 isn't > 0 then let me know what they are.

**Comment by rmoshe** [comment]
rc: 403
responseLength = undefined

**Comment by dyoungzenoss** [comment]
On line 73 what's displayed for the value of the _text:_ field?  It should be some sort of error message.

**Comment by rmoshe** [comment]
obj = Object {text: "Requests to https://reduxio.testrail.com//index.ph…tion (http://confluence.atlassian.com/x/KQfCDQ ).", rc: 403, headers: Object,...

**Comment by rmoshe** [comment]
I Thing I got something:
"Requests to https://reduxio.testrail.com//index.php?/api/v2/get_statuses are not allowed.  See your administrator about configuring a whitelist entry for this destination (http://confluence.atlassian.com/x/KQfCDQ )."

**Comment by dyoungzenoss** [comment]
Ah, excellent.  In JIRA, you (or an administrator, if you're not one) can click the "gear" icon on the top right, next to your avatar, to open the Adminstration dropdown. Click on System.  On the System page click Whitelist in the menu on the left.  At the top of the whitelist enter _https://reduxio.testrail.com/*_ in the Expression field and click Add.  The Type should have automatically selected Wildcard expression.

Retry viewing the Dashboard.

**Comment by rmoshe** [comment]
Did it, Still getting the same error....

**Comment by rmoshe** [comment]
Its Working !!!
I had to remove the gadget and add it again....

Thanks for all the help !

Now we need to debug some real (Red) issues like:
ifr?container=atlassian&mid=16140&country=US&lang=en&view=default&view-params={"writable"%3A"true"}…:122 GET http://gadget.server.hostname/gadgets/testrail-projects-all-summary.js net::ERR_NAME_NOT_RESOLVED

testrail-project-summary.js:277 Uncaught TypeError: google.visualization.arrayToDataTable is not a constructor
    at renderTestResults (testrail-project-summary.js:277)
    at handlePlanResponse (testrail-project-summary.js:239)
    at processResponse (auth-refresh.js?v=5d17277…&container=atlassian&debug=0:327)
    at XMLHttpRequest.<anonymous> (auth-refresh.js?v=5d17277…&container=atlassian&debug=0:70)

**Comment by dyoungzenoss** [comment]
If that's the real error then the gadget server URL needs to be updated with your gadget server hostname.

**Comment by dyoungzenoss** [comment]
And I get the arrayToDataTable error occasionally, but I haven't been able to debug why. It goes away if you refresh the page.

**Comment by dyoungzenoss** [comment]
And I'm going to update the install instructions to include the need to update the JIRA whitelist.

**Comment by rmoshe** [comment]
Fixed the hostname error...

These are the real ones:
,,,Uncaught TypeError: google.visualization.DataTable is not a constructor
    at renderTestResults (testrail-plan-or-run-summary.js:192)
    at handlePlanOrRunResponse (testrail-plan-or-run-summary.js:176)
    at processResponse (auth-refresh.js?v=5d17277…&container=atlassian&debug=0:327)
    at XMLHttpRequest.<anonymous> (auth-refresh.js?v=5d17277…&container=atlassian&debug=0:70)
renderTestResults @ testrail-plan-or-run-summary.js:192
handlePlanOrRunResponse @ testrail-plan-or-run-summary.js:176
processResponse @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:327
(anonymous) @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:70
XMLHttpRequest.send (async)
makeXhrRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:354
makeRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:390
fetchPlanResults @ testrail-plan-or-run-summary.js:153
handleProjectResponse @ testrail-plan-or-run-summary.js:138
processResponse @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:327
(anonymous) @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:70
XMLHttpRequest.send (async)
makeXhrRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:354
makeRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:390
fetchProjectInfo @ testrail-plan-or-run-summary.js:124
handleStatusResponse @ testrail-plan-or-run-summary.js:104
processResponse @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:327
(anonymous) @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:70
XMLHttpRequest.send (async)
makeXhrRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:354
makeRequest @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:390
fetchStatusList @ testrail-plan-or-run-summary.js:66
runOnLoadHandlers @ auth-refresh.js?v=5d17277…&container=atlassian&debug=0:82
(anonymous) @ ifr?container=atlassian&mid=16145&country=US&lang=en&view=default&view-params={"writable"%3A"true"}…:125
,,,

**Comment by rmoshe** [comment]
And BTW - There is no support for nested milestones

**Comment by dyoungzenoss** [comment]
I'll look into the constructor error above.

The milestone XML you posted above has the following:

```
<UserPref name="projectMilestoneIDList" display_name="(Project) Milestone" datatype="enum" default_value="1|10">
   <EnumValue value="1|10" display_value="(XXXX) V3.0 Integration"/>
   <EnumValue value="1|12" display_value="(XXXX) V3.0GA"/>
   <EnumValue value="1|13" display_value="(XXXX) V3.0GA\V3-Cycle1"/>
   <EnumValue value="1|14" display_value="(XXXX) V3.0GA\V3-Cycle2"/>
   <EnumValue value="1|15" display_value="(XXXX) V3.0GA\V3-Cycle3"/>
</UserPref>
```

Those last 3 entries are nested milestones.

**Comment by rmoshe** [comment]
The nested milestones cannot be selected in the milstone status gadget.
The milestone status gadget is stuck...

I must head out... Thanks for the help...
Waiting to hear about those errors ...

Thank you for your help !

**Comment by rmoshe** [comment]
Don't know how to get a hold of you if not here...
I see you have 2 new branches - will they get merged to master soon ?

Thanks !

**Comment by dyoungzenoss** [comment]
Yes, they're being code-reviewed and should be merged today.  One is just the updated install instructions and the other is the fix for the uncaught TypeError.

**Comment by rmoshe** [comment]
Super ! Thanks for your quick response and time !

**Comment by dyoungzenoss** [comment]
Code fix has been merged for the uncaught TypeError. To verify:

1. Download the latest .js files
1. Replace the .js files on the gadget server with the new ones
1. Clear your browser cache
1. Delete the gadget from your JIRA dashboard and re-add it

You should see the charts.

**Comment by rmoshe** [comment]
The issue is now resolved.
Please close as fixed.
I have more issues - how can we discuss ?

**Comment by dyoungzenoss** [comment]
Glad this is fixed. For the other issues just create a new issue here.

**Comment by sipani909** [comment]
Am seeing this issue even after whitelisting the testrail URL. Does integration need to be enabled between testrail and JIRA for this gadget to work?

**Comment by sipani909** [comment]
Debugging according to steps above shows the following:
obj = {text: "", rc: 500, headers: {…}, oauthApprovalUrl: undefined, oauthError: undefined}
